// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3qCX3HB1_wHpeRUBFg_vsBSvueqEtA4g',
    appId: '1:676225573875:web:c2c80ae1b9b1dc1d2a6886',
    messagingSenderId: '676225573875',
    projectId: 'sc-marketplace-a5719',
    authDomain: 'sc-marketplace-a5719.firebaseapp.com',
    storageBucket: 'sc-marketplace-a5719.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtaNIw2Qxe7hFEbj7zmQhXhbUHI9iL5BM',
    appId: '1:676225573875:android:b37162a958494e982a6886',
    messagingSenderId: '676225573875',
    projectId: 'sc-marketplace-a5719',
    storageBucket: 'sc-marketplace-a5719.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl6u0aURVnR6CYmQIouoZeu5HCniMuiyo',
    appId: '1:676225573875:ios:8d4ae73e551477e12a6886',
    messagingSenderId: '676225573875',
    projectId: 'sc-marketplace-a5719',
    storageBucket: 'sc-marketplace-a5719.appspot.com',
    iosClientId: '676225573875-kr9fi36qa1bo9p0p7ms06vql4ii1cpk0.apps.googleusercontent.com',
    iosBundleId: 'com.example.scmarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl6u0aURVnR6CYmQIouoZeu5HCniMuiyo',
    appId: '1:676225573875:ios:63ca0769d405dfee2a6886',
    messagingSenderId: '676225573875',
    projectId: 'sc-marketplace-a5719',
    storageBucket: 'sc-marketplace-a5719.appspot.com',
    iosClientId: '676225573875-v5kc7aq8fbjp07bvom5s77udbonogo5n.apps.googleusercontent.com',
    iosBundleId: 'com.example.scmarketplace.RunnerTests',
  );
}
